server:
  port: 8086
  servlet:
    context-path: /testfreemark
spring:
  application:
    name: testfree
  freemarker:
    prefix: .html
    cache: false
    request-context-attribute: request
    expose-session-attributes: true


