server:
  port: 8085
spring:
  application:
    name: eureka-feign
  freemarker:
    prefix: .html
    cache: false
    request-context-attribute: request
    expose-session-attributes: true
    template-loader-path: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf-8
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/





